### ISSUE TITLE
Series value "-1" not displayed

### ISSUE THREAD

**Issue by nrbrt** [hotNipi/node-red-contrib-ui-statechart#1]
Hi,
I am having an issue with a series (for instance A) with a value of -1. I use -1 to indicate that a sensor is not responding or not present. When that happens after another value was displayed first in that series, that old value remains visible. When I use a value of -2 or -1.1, things work as expected. "-1" seems to be a special case.

So when I send this msg.payload:
`[{series:"C1",value:22.5,state:true},{series:"C2",value:23.9,state:true},{series:"C3",value:45.6,state:true},{series:"C4",value:95.4,state:true},
                {series:"C5",value:95.4,state:true},{series:"IN",value:15.6,state:true},{series:"OUT",value:94.2,state:true}]`
and then this one:
`[{series:"C1",value:22.5,state:true},{series:"C2",value:23.9,state:true},{series:"C3",value:45.6,state:true},{series:"C4",value:-1,state:true},
                {series:"C5",value:95.4,state:true},{series:"IN",value:15.6,state:true},{series:"OUT",value:94.2,state:true}]`
The C4 series does not show -1, but 95.4. But like I said, when I change the value to -1.1 or -2 things work fine. I do not expect the graphical bar itself to go negative by the way, just the negative value displayed.

Great work on the node and I would appreciate any help that you could offer.

**Comment by hotNipi** [comment]
Seems like edge case. Will investigate for sure.

**Comment by hotNipi** [comment]
And the bug found and fixed.
Version 0.1.4 available. 

Wasn't really that much edge case. But nobody ever hit it with value = -1 (or didn't rise the issue)
In case of value == -1  there is logarithm calculation which leads to 
`Math.log(0)`
That ends with `-Infinity`.
