### ISSUE TITLE
A couple of minor requests

### ISSUE THREAD

**Issue by riprock67** [hotNipi/node-red-contrib-ui-statechart#2]
This is a great node!  Thanks!  I had some minor requests, and was wondering if they could be implemented:

1)  Could you implement an option to round the values shown on the chart to an integer?  Or some number of digits?  Three digits of precision just clutters the chart in my case.  I can see where to do this in the js code, but I am not sure how to recompile it into a local node for myself.

2)  It would be great if the range could be set and shown on the left hand side, like a regular chart.  In my case, I would like to show numbers from 0 to 100, with ticks every 25 units, even if none of my values reach 100.  As the charting js is also new to me, I cant see how to do this, and even if I could (as I stated in 1 above), I am not clear on how to  compile this into a node I could use (even if only locally).

Any thoughts are very much appreciated!

**Comment by hotNipi** [comment]
1. There is too many ways the value formatting may be wanted so I don't want to open a pandoras box here. But you can do it for yourself easily.

Here is commented version of the functionality.
```

// inside the function 
var updateValues = function () ...

// find this part:

d = $scope.data[i].value // the actual value

// the tl variable is used to calculate number of digits to appear after the decimal point. 0.00 or 10.0 or 100 ...

if(d === -1){ // special case for natural logarithm from -1
	tl = 3 
}
else{
	tl = Math.ceil(Math.log(d + 1) / Math.LN10); // the full magic of the natural logarithm. 
}																
if(tl > 3){
	d = parseFloat(d/1000).toFixed(1)+'k' // in case of too much digits (to many characters just can't be fitted) the value is shown as 2k or similar
}
else{
	d = d.toFixed(3-tl) // regular case
}													
target.setAttributeNS(null,'y',yp)	// adjust the position of the text						
$(target).text(d) // set actual text 
```
Feel free to change it. 

To make your own version of the node, just fork it, change it, and install it to node red from your local version of the node.
If you are using windows then it goes like this. 

stop node red
run **cmd.exe** where:
navigate to the node red directory `C:\Users\your-user-name\.node-red`
and install the node
`npm install C:\the-full-path\to-your-version\of-the\node-red-contrib-ui-statechart`

run node red and see if your changes applied.


2. That would make it just as the regular chart. As the regular chart already exists - I cant see any reason to do it.

If you need to do custom charts, the I'd recommend to use the **d3.js** library where you have everything under your control. It is not easy but the web is full of examples.

**Comment by riprock67** [comment]
Dear HN,

I figured out how to modify a local variant of your code to achieve what I wanted (values rounded to integers).  However, I couldn't quite figure out how to force the range to run from 0 to 100.  I tried modifying lines 321-322:

				config.min = Number.MAX_VALUE
				config.max = Number.MIN_VALUE
				
				updateData()				
				

to:

				config.min = 0
				config.max = 100
				
				updateData()				
				
But nothing actually changed.  Can you give me a hint as to the line number I should be looking at for a change?

Also, I dont see how to add a y-axis.  Any chance you might give me a hint on pursuing that as well?

Thanks,

Scott

*************************************************************************************
Dr. F. Scott Anderson						Tel:		(720) 240-0127
Southwest Research Institute					Ofc:		(303) 546-9670
1050 Walnut St, Suite 300 					Cell:		(808) 224-4734
Boulder, CO 80302 						Fax:		(303) 546-9687
http://www.boulder.swri.edu/ <http://www.boulder.swri.edu/>
*************************************************************************************
All opinions herein stated are mine, not those of SwRI or NASA.  Trust me.

**Comment by hotNipi** [comment]
That's because of this chart is kind of special.
Every input calls the function updateData, which then calculates new values for min and max.

![image](https://user-images.githubusercontent.com/35291460/170767948-6bf6fe94-0dc5-4d54-a95a-ad656b8f3fe5.png)

If you want them to be stable just remove those statements. And be sure your data is inside min and max if you don't want to see overshoots for bars.

How to make y-axis. It is kind of complicated to explain
First of all, you'll need to draw a horizontal line(s) inside the svg. Then you'll need to position it vertically using the range calculation. then may be you'll need to labels for them. Those also need positioning. 

Knowing nothing about how you exactly need them I can't go deep into the code. It also takes even for me an hour or so to finalize but I'm kind of busy for such freelancing currently.

Examine the code and find how to draw things with the svg and you are on half way. If stuck, show what you have done and ask help on topic.

**Comment by riprock67** [comment]
Thanks HN.

I understand the range bit, and will set it now.

As for the SVG, a lot of learning will need to happen.  Maybe I will let it go for now!

Thanks again,

S-

**Comment by riprock67** [comment]
Dear HN,

In looking at the result of fixing the range, and the forcing only integer values, I am happy with the result.  It is a simple, clean graphical presentation.  Thanks for helping me out!

S-

**Comment by riprock67** [comment]
OK - thanks.  I will figure out how to download your code, and modify it to do these relatively trivial things.  Thanks for creating these basic graphs so I have some examples to build on.

Sincerely,

RipRock
