### ISSUE TITLE
Feature request, Y scale 0 to MAX

### ISSUE THREAD

**Issue by CirruZZ** [hotNipi/node-red-contrib-ui-statechart#3]
Hi, juist found your node, simple and just what I was looking for.

Would it be possible to add an option to have the Y axis scale from **0** to MAX, instead as of now **MIN** to MAX?

![image](https://user-images.githubusercontent.com/480883/204131520-9f8a0143-7e52-409e-b3b7-69863a946ae3.png)

that would be more intuitiv when interpreting the states as they also (in my case) relate to the value. (Using it to visualize price automations)

**Comment by hotNipi** [comment]
What will happen if the minimum is forced to zero but the incoming data contains negative vaules?

**Comment by CirruZZ** [comment]
Sorry I don't understand? Is there a possibility to force min to zerro?

**Comment by CirruZZ** [comment]
> What will happen if the minimum is forced to zero but the incoming data contains negative vaules?

In that case, I guess MIN should be the negative value. That's how it usually works in other charting tools.

If MIN>0, Ymin = 0, else, Ymin=MIN

**Comment by hotNipi** [comment]
OK. But if min value is configurable it should be configurable to any value. Just I can't see the reason to allow only 0 (zero). And if the min value is configurable, why not the max value. Behavior is same, if some incoming value is bigger than the configured max, the max will be highest value in the data array.

I pretty much agree to make it happen. It will be optional and min - max configuration will be hidden unless you select a checkbox at the config page where you change default behavior to the configurable min-max. 

But as you are requesting the feature - can you do the most important part of the job - to make all necessary changes for help file to describe that new behavior?

**Comment by CirruZZ** [comment]
Absolutely with you, it was just what I was looking for. Expanding the feature to both MIN and MAX sounds great.  

No problem, I will!

**Comment by hotNipi** [comment]
I'll try to work with it tomorrow as today is 1 Advent so I'll spend my time with family.

**Comment by hotNipi** [comment]
The feature is actually implemented. Released version 0.2.0-beta.0 just to get help from some of my friends on testing ..

**Comment by CirruZZ** [comment]
That was quick!
Bear with me, I'm just used to install nodes from palette. How can I install 0.2.0-beta.0 ?

**Comment by hotNipi** [comment]
Depending on your op system but - with some terminal (CMD, Powershell, ...) go to .node-red directory and run command "npm i node-red-contrib-ui-statechart@0.2.0-beta.0"

**Comment by CirruZZ** [comment]
> Depending on your op system but - with some terminal (CMD, Powershell, ...) go to .node-red directory and run command "npm i node-red-contrib-ui-statechart@0.2.0-beta.0"

Using Docker via Portainer, after some searching I found the correct dir, got it installed.

With positive values, everything seems to work. If you also include a negative value, it looks strange. Don't know if it is supposed to work with negative values as well? Then you want the bar to go from Y=0 downwards.

**Comment by hotNipi** [comment]
I think you mean something like this for negative values.

![image](https://user-images.githubusercontent.com/35291460/204380130-07572058-a7de-4b0a-810f-c5ef14d71fa3.png)

Even it is nice but it goes too far from target. The target is the relation between values together with states. And that's it. The limits on min max is already a bit on the edge. 
There is many chart libraries which can do it. For example I use the chartist library where you can make your own rules how to colorize bars. (Well I don't use the dashboard at all but that's not the point)

![image](https://user-images.githubusercontent.com/35291460/204382248-b8d332df-1b54-49b3-ab36-70adb50729d9.png)

But this node is created to be lightweight and targeted to be easy to use even for youngsters and it must do only what it says - no way to make it to be as chart - full of options.

**Comment by hotNipi** [comment]
With settings like this 
![image](https://user-images.githubusercontent.com/35291460/204383314-31dc15b1-e520-42c9-9f1a-3c3f300b603c.png)

The value below configured min just makes the min to be lowest value. 

![image](https://user-images.githubusercontent.com/35291460/204383576-bb48cd1a-7dc1-4e8e-9dbf-ce05ee9810af.png)

**Comment by CirruZZ** [comment]
> I think you mean something like this for negative values.
> 
> ![image](https://user-images.githubusercontent.com/35291460/204380130-07572058-a7de-4b0a-810f-c5ef14d71fa3.png)

Yes exactly.

No problem! It's just that you mentioned negative values earlier, there of my question.
> What will happen if the minimum is forced to zero but the incoming data contains negative vaules?

Totally agree with you, keep it simple.

**Comment by hotNipi** [comment]
Let's say it this way - if you do configure some limits you are expecting the data to be in those boundaries. And then if there is abnormalities - the chart will not crash but adapts, still trying to stay on target - showing how the values relate always in same manner.

**Comment by CirruZZ** [comment]
> But as you are requesting the feature - can you do the most important part of the job - to make all necessary changes for help file to describe that new behavior?

Suggestion for the documentation

_By default the graph will be autoscaling so that it will adjust the y-axis to the range of the data. You can change this behavior by explicitly setting the limits. To do this uncheck **Use dataset min & max**  checkbox and specify custom limits. The y-axis will then range at least from **Min** to **Max**. Autoscaling will still permit those boundaries to be stretched if the dataset exceeds the specified limits._

**Comment by hotNipi** [comment]
Beautiful :)

**Comment by hotNipi** [comment]
You may suggest the better wording for config page also if it feels somehow not too clear or correct.

**Comment by hotNipi** [comment]
Tip: If you set the limits - you may leave one of them unspecified (empty). May be also mentioned in help

**Comment by CirruZZ** [comment]
> Beautiful :)

Thanks!



> You may suggest the better wording for config page also if it feels somehow not too clear or correct.

I'll think about it, for now it seems good.


> Tip: If you set the limits - you may leave one of them unspecified (empty). May be also mentioned in help



_By default the graph will be autoscaling so that it will adjust the y-axis to the range of the data. You can change this behavior by explicitly setting the limits. To do this uncheck **Use dataset min & max** checkbox and specify custom limits. One or both limits can be specified. If only one limit is specified, the other will still autoscale. The y-axis will then range at least from **Min** to **Max**. Autoscaling will still permit those boundaries to be stretched if the dataset exceeds the specified limits._

**Comment by hotNipi** [comment]
Published  0.2.0-beta.2 with docs updated. I still wait for feedback from my testers. It shouldn't take long :)

**Comment by CirruZZ** [comment]
Awesome!

I have some other suggestions that I think are within the scope of statechart, I'll put them in separate issues.

**Comment by hotNipi** [comment]
My tester approved :)

**Comment by hotNipi** [comment]
v0.2.0 published
