### ISSUE TITLE
Option to set color per bar

### ISSUE THREAD

**Issue by CirruZZ** [hotNipi/node-red-contrib-ui-statechart#5]
The input `msg.payload` should carry an array of Object(s) where required properties are:
`series` - (string) name of series
`value` - (number) value
`state` - (boolean) state

Suggestion is to have an optional Object that sets the color for the bar. This would override the `state` and the colors defined in config.

optional `color` - (string) color of bar
Format of string could be either HEX or Name. 
https://www.w3schools.com/colors/colors_names.asp
https://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes

Example
![6c391390199635f7b4ed656c038cdc7250b1df05](https://user-images.githubusercontent.com/480883/204488931-86e01bce-d9bb-435b-a135-b3364a138c4a.png)

**Comment by hotNipi** [comment]
With 0.2.0-beta.3 color per bar from incoming message.

Test flow: 
```
[{"id":"1fb35f29bb459e80","type":"ui_button","z":"bf0d83d32eec75c2","name":"","group":"898de908ad30abec","order":0,"width":0,"height":0,"passthru":false,"label":"random","tooltip":"","color":"","bgcolor":"","className":"","icon":"","payload":"","payloadType":"date","topic":"topic","topicType":"msg","x":160,"y":600,"wires":[["92d2c250e5ae9cc1"]]},{"id":"92d2c250e5ae9cc1","type":"function","z":"bf0d83d32eec75c2","name":"data","func":"let letters = [\"A\",\"B\",\"C\",\"D\",\"E\"]\nlet colors = ['red','#00CC45','RGB(100,50,64)','yellow']\nlet p = []\nfor(let i =0; i<letters.length;i++){\n    p.push({ series: letters[i], value: ((Math.random()* 10)), state: Math.random() > .5,color:colors[i]})\n}\nmsg.payload = p \nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":310,"y":600,"wires":[["e1f943da427e600d"]]},{"id":"e1f943da427e600d","type":"ui_statechart","z":"bf0d83d32eec75c2","group":"898de908ad30abec","order":1,"width":"6","height":"4","name":"","label":"STATES","series":"A,B,C,D,E","showvalues":true,"colorON":"#009933","colorOFF":"#00b3ff","colorFromTheme":false,"fontColorFromTheme":true,"textoptions":"default","colorText":"#eeeeee","fontLabel":"","fontValue":"","fontSeries":"","minValue":"0","maxValue":"8","limitChoice":false,"x":470,"y":600,"wires":[]},{"id":"898de908ad30abec","type":"ui_group","name":"Default","tab":"64e6b44ee969957e","order":1,"disp":true,"width":"6","collapse":false,"className":""},{"id":"64e6b44ee969957e","type":"ui_tab","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]

```

**Comment by CirruZZ** [comment]
Just awesome. Development in lightning speed.

 I'll try to write some documentation.

**Comment by CirruZZ** [comment]
> I'll try to write some documentation.

Suggestion for documentation

The input `msg.payload` should carry an array of Object(s) where required properties are:
`series` - (string) name of series
`value` - (number) value
`state` - (boolean) state
Optional object
`color` - (string) color of bar

color Object sets the color for the bar. This overrides the `state` and the colors defined in config. Acceptet definition of color is text, RGB or hex (e.g  `red` , `RGB(100,50,64)`,  `#00CC45`)

![Skärmbild 2022-11-30 094044](https://user-images.githubusercontent.com/480883/204748360-3b91e0e3-d78e-47f7-92e5-eb5ac1e875ca.png)

**Comment by hotNipi** [comment]
Thanks. I'll do my best to make changes but I can't promise it will happen today. A bit busy with may real job ..

**Comment by CirruZZ** [comment]
No worries, I just promised to help ;-)

**Comment by hotNipi** [comment]
https://flows.nodered.org/node/node-red-contrib-ui-statechart v0.2.0 is available so the install via palette manager should be possible.
Thanks for your contribution. It was a pleasure working with you.
